version: 0.2
env:
  variables:
    S3_BUCKET: "www.iamstarman.com"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - npm run test
      - npm run build:prod
  post_build:
     commands:
      - aws s3 cp dist/apps/ui s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes